### ISSUE TITLE
Missing payment-service.yaml file

### ISSUE THREAD

**Issue by bakaroni** [xtreamsrl/interviews-back-end-assignment#4]
Dear team,

according to the challenge 3 there is supposed to be a file `payment-service.yaml`:

> If the user has enough money, the API will return a success message, otherwise, it will return an error message. An external service must be used to get the money from the user: you can find the swagger documentation in the file `payment-service.yaml`.

but no such file is included in the repo. I do not intend to ask details about the challenges, I just felt like the file was not omitted on purpose (but maybe I'm wrong).

Thanks in advance.

**Comment by rams23** [comment]
Hi, thanks for reporting. I added it
